name: decomposition_pipeline_test

on: # workflow_dispatch
 push:
   branches: [ "main", "**" ]
 pull_request:
   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
       python-version: ["3.9", "3.10", "3.11"]
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry pipreqs black addheader pytest-cov pip-licenses types-pkg-resources==0.1.3
        poetry install
    # - name: black check
    #   run:  |
    #       black --check .
    - name: Run tests and coverage
      run: |
         poetry run pytest 
    #- name: 'Dependency Review'
    #  uses: actions/dependency-review-action@v4
    #    # Commonly enabled options, see https://github.com/actions/dependency-review-action#configuration-options for all available options.
    #  with:
    #     comment-summary-in-pr: always

    - name: License check
      run: |
        pip-licenses --format=markdown --order=license
        
    - name: SPDX check
      run: |
       addheader -t header.txt .
       grep -L -f header.txt */*.py
